### PR TITLE
switch back to library names from find_package

### PR DESCRIPTION
**Pull request by remicollet**
### 1/ build issue 

```
CMake Error at lib/CMakeLists.txt:5 (add_library):
  Target "zip" links to target "LibLZMA::LibLZMA" but the target was not
  found.  Perhaps a find_package() call is missing for an IMPORTED target, or
  an ALIAS target is missing?
```
also
```
  Target "zip" links to target "BZip2::BZip2" but the target was not found.
  Perhaps a find_package() call is missing for an IMPORTED target, or an
  ALIAS target is missing?
```

### 2/ pkgconfig usability

**1.7.1:**
`-Libs.private:  -lz -lbz2 -llzma -lssl -lcrypto`

**1.7.2:**
`Libs.private:  -lBZip2::BZip2 -lLibLZMA::LibLZMA -lOpenSSL::Crypto -lZLIB::ZLIB`

### CODE REVIEW

**Comment by 0-wiz-0** [comment]
Thanks for the report.
Please just fix the pkgconfig file and leave the other files as-is.

**Comment by remicollet** [comment]
> Please just fix the pkgconfig

But first issue is not related to pkgconfig, but to libzip build

**Comment by 0-wiz-0** [comment]
Please provide more details. The travis builds on Linux work fine.

**Comment by 0-wiz-0** [comment]
Or perhaps your liblzma is too old. Which version do you have installed?

**Comment by remicollet** [comment]
It fails for **liblzma** on RHEL/CentOS 8, using version 5.2.4

If fails foir **libbz2** on RHEL/ CentOS 6, using version 1.0.5

**Comment by 0-wiz-0** [comment]
Which cmake version?
cmake 3.17 (at least, probably older versions too) provide
````
.../share/cmake-3.17/Modules/FindBZip2.cmake
.../share/cmake-3.17/Modules/FindLibLZMA.cmake
````

**Comment by remicollet** [comment]
cmake  3.17.3 on Fedora
cmake 3.11.4 on EL-8
cmake 3.6.1 on EL-6

**Comment by remicollet** [comment]
On EL-8, `FindLibLZMA.cmake `exists but doesn't provide the `LibLZMA::LibLZMA` stuff.

**Comment by 0-wiz-0** [comment]
Can you please try
https://github.com/nih-at/libzip/commit/992ed23c322c9abb9a108a6d119c09aada50ca9c ?

**Comment by remicollet** [comment]
> Can you please try 992ed23 ?

This fix build on EL-8

Still broken on EL-6

```
CMake Error at cmake-compat/CheckLibraryExists.cmake:38 (include_guard):
  Unknown CMake command "include_guard".
Call Stack (most recent call first):
  CMakeLists.txt:28 (include)

```

And pkgconfig.pc is still broken.

**Comment by 0-wiz-0** [comment]
I tried fixing the pkgconfig file already in https://github.com/nih-at/libzip/commit/4fdcd241a48387d1a3aecd04ca25a115a9a689f6

**Comment by 0-wiz-0** [comment]
And for EL-6 try https://github.com/nih-at/libzip/commit/f520e28292d112ab1bd52d41567d89fb98cc5090

**Comment by remicollet** [comment]
Using 1.7.2 + 4fdcd241a48387d1a3aecd04ca25a115a9a689f6 + 992ed23c322c9abb9a108a6d119c09aada50ca9c + ebe01b5c259fa28b4da24cc1c11ab24a31281b64 + f520e28292d112ab1bd52d41567d89fb98cc5090

Build **OK** on Fedora 30 to 32 and RHEL 6 to 8

**Comment by 0-wiz-0** [comment]
Thanks for testing!
Sorry for the breakage, but I really wanted to follow cmake best practices, and it made some other stuff easier.

**Pull request closed without merging**
