### PR TITLE
fixed build error when linking to static OpenSSL

### PR DESCRIPTION
**Pull request by dktapps**
…er means)

this was not linking to dl when building if the library path was overridden.

Example:
```
 cmake . -DCMAKE_PREFIX_PATH=/home/dktapps/php-build-scripts/bin/php7
```
where the target directory contained installations of zlib and openssl produced the following
```
[ 89%] Building C object src/CMakeFiles/zipcmp.dir/zipcmp.c.o
[ 91%] Building C object src/CMakeFiles/ziptool.dir/ziptool.c.o
[ 91%] Building C object src/CMakeFiles/zipmerge.dir/zipmerge.c.o
[ 92%] Building C object regress/CMakeFiles/fopen_unchanged.dir/fopen_unchanged.c.o
[ 92%] Linking C executable fopen_unchanged
[ 92%] Linking C executable zipmerge
[ 92%] Linking C executable zipcmp
[ 92%] Linking C executable ziptool
../lib/libzip.so.5.0: undefined reference to `dlopen'
../lib/libzip.so.5.0: undefined reference to `dlclose'
../lib/libzip.so.5.0: undefined reference to `dlerror'
../lib/libzip.so.5.0: undefined reference to `dlsym'
../lib/libzip.so.5.0: undefined reference to `dladdr'
collect2: error: ld returned 1 exit status
src/CMakeFiles/ziptool.dir/build.make:98: recipe for target 'src/ziptool' failed
make[2]: *** [src/ziptool] Error 1
CMakeFiles/Makefile2:469: recipe for target 'src/CMakeFiles/ziptool.dir/all' failed
make[1]: *** [src/CMakeFiles/ziptool.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
../lib/libzip.so.5.0: undefined reference to `dlopen'
../lib/libzip.so.5.0: undefined reference to `dlclose'
../lib/libzip.so.5.0: undefined reference to `dlerror'
../lib/libzip.so.5.0: undefined reference to `dlsym'
../lib/libzip.so.5.0: undefined reference to `dladdr'
collect2: error: ld returned 1 exit status
src/CMakeFiles/zipcmp.dir/build.make:98: recipe for target 'src/zipcmp' failed
make[2]: *** [src/zipcmp] Error 1
CMakeFiles/Makefile2:395: recipe for target 'src/CMakeFiles/zipcmp.dir/all' failed
make[1]: *** [src/CMakeFiles/zipcmp.dir/all] Error 2
../lib/libzip.so.5.0: undefined reference to `dlopen'
../lib/libzip.so.5.0: undefined reference to `dlclose'
../lib/libzip.so.5.0: undefined reference to `dlerror'
../lib/libzip.so.5.0: undefined reference to `dlsym'
../lib/libzip.so.5.0: undefined reference to `dladdr'
collect2: error: ld returned 1 exit status
regress/CMakeFiles/fopen_unchanged.dir/build.make:98: recipe for target 'regress/fopen_unchanged' failed
make[2]: *** [regress/fopen_unchanged] Error 1
CMakeFiles/Makefile2:615: recipe for target 'regress/CMakeFiles/fopen_unchanged.dir/all' failed
make[1]: *** [regress/CMakeFiles/fopen_unchanged.dir/all] Error 2
../lib/libzip.so.5.0: undefined reference to `dlopen'
../lib/libzip.so.5.0: undefined reference to `dlclose'
../lib/libzip.so.5.0: undefined reference to `dlerror'
../lib/libzip.so.5.0: undefined reference to `dlsym'
../lib/libzip.so.5.0: undefined reference to `dladdr'
collect2: error: ld returned 1 exit status
src/CMakeFiles/zipmerge.dir/build.make:98: recipe for target 'src/zipmerge' failed
make[2]: *** [src/zipmerge] Error 1
CMakeFiles/Makefile2:432: recipe for target 'src/CMakeFiles/zipmerge.dir/all' failed
make[1]: *** [src/CMakeFiles/zipmerge.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2
```

### CODE REVIEW

**Comment by 0-wiz-0** [comment]
Only `regress/malloc.c` uses `dlsym()`. The other symbols mentioned above are not used at all by libzip.

Please explain why the symbols are referenced in your build of `libzip.so.5.0`.

**Comment by dktapps** [comment]
I do not know. I cloned the repository directly and followed the standard build instructions, with the exception of changing the prefix path.

**Comment by 0-wiz-0** [comment]
On what platform/operating system?

**Comment by dktapps** [comment]
Ubuntu 16.04. FWIW, the compilation proceeds successfully on MacOS.

**Comment by 0-wiz-0** [comment]
I still believe this is something in your compilation environment, for the reasons listed above. Also, travis successfully builds libzip on Ubuntu 14.04.5 LTS.
Please check your compilation environment.
Why do you set `CMAKE_PREFIX_PATH`? Perhaps that's the problem?

**Comment by dktapps** [comment]
The build I'm creating is intended to link to non-system versions of zlib and openssl for distribution purposes (this is for a crap build system). As I said, the same problem occurs when LDFLAGS is used to change the install prefix.

I've encountered this problem on two separate machines both running 16.04.

When the library path is _not_ overridden, everything is fine. It's only when the path is overridden that this problem starts to rear its head.

The build is being done by [this script](https://github.com/pmmp/php-build-scripts/blob/php/7.3/compile.sh#L661-L674). I have also reproduced this process outside of this script, so I am sure the script is not at fault.

**Comment by dktapps** [comment]
Running `nm` on the output binary tells me that the .so with custom prefix has dl* symbols, while the standard one doesn't. My mistake, it seems I have some other issue here.

**Comment by dktapps** [comment]
The problem is coming from linking to an OpenSSL static library which contains those symbols.

**Comment by 0-wiz-0** [comment]
Sorry, I still don't think that this is a problem in libzip.
If your openssl library needs `-ldl`, then it should pull it in.

**Pull request closed without merging**
