### PR TITLE
Exclude the tests that do not work under Windows

### PR DESCRIPTION
**Pull request by OgreTransporter**
Discussion: #166

### CODE REVIEW

**Comment by dillof** [comment]
runtest checks wether all features required for a test are present on the current build platform, and skips the test if not. Maintaining a list of tests that should not be run for each setting does not scale well.

runtest should skip tests on Windows that require preloading a library, and it works in the AppVeyor builds. We should figure out why this does not work in your case.

**Comment by OgreTransporter** [comment]
> We should figure out why this does not work in your case.

Okay, what do you want me to do?

**Comment by dillof** [comment]
I've just seen that we don't explicitly skip preload tests on Windows, I don't really understand why it works in AppVeyor. I committed a fix for this, could you please try again and see if the encrypt-nonrandom and preload tests are skipped now?

**Comment by OgreTransporter** [comment]
Your fix is working
```
1>The following tests did not run:
1>	  7 - add_from_stdin.test (Skipped)
1>	126 - clone-fs-add.test (Skipped)
1>	127 - clone-fs-delete.test (Skipped)
1>	128 - clone-fs-replace.test (Skipped)
1>	129 - fdopen_ok.test (Skipped)
1>	130 - encryption-nonrandom-aes128.test (Skipped)
1>	131 - encryption-nonrandom-aes192.test (Skipped)
1>	132 - encryption-nonrandom-aes256.test (Skipped)
1>	133 - encryption-nonrandom-pkware.test (Skipped)
1>	134 - preload.test (Skipped)
1>
1>The following tests FAILED:
1>	  6 - add_from_filep.test (Failed)
```

**Comment by 0-wiz-0** [comment]
About `add_from_filep` - that is an executable that is built in `regress`. Please check your path why it's not found, while others (like e.g. `fread` for `fread.test`) are.

**Pull request closed without merging**
