### PR TITLE
add zip_get_version  and zip_get_version_id functions 

### PR DESCRIPTION
**Pull request by remicollet**
to retrieve runtime version (which may differ from buildtime version when ABI is compatible)

### CODE REVIEW

**Comment by 0-wiz-0** [comment]
We have added a `zip_libzip_version()` function that returns the version string.
We don't really understand the need or point of the other functions, can you please explain your use case?

**Comment by remicollet** [comment]
> We don't really understand the need or point of the other functions,

Bah... just something quite commonly used in other libraries.

BTW zip_libzip_version is enough for my needs.

**Comment by remicollet** [comment]
BTW use case

```
if (zip_get_version_id(0) >= 0x130) {
  // use BZ2 compression 
} else {
  // use other compression
}
```

**Comment by 0-wiz-0** [comment]
That use case does not work: bzip2 support is a compile-time option, so you can have a new libzip without bzip2 support.

**Pull request closed without merging**
