### PR TITLE
Add a toolchain for publishing to NuGet

### PR DESCRIPTION
**Pull request by Silver-Fang**
Not sure if maintainers are interested in this?

### CODE REVIEW

**Comment by dengchj** [comment]
Maybe English is more common.

**Comment by Silver-Fang** [comment]
> Maybe English is more common.

I'll deal with that. But what about this appveyor failure?

**Comment by dillof** [comment]
> > Maybe English is more common.
> 
> I'll deal with that. But what about this appveyor failure?

Don't worry about that, one of the dependencies fail to install and we haven't had the time to sort that out yet.

**Comment by 0-wiz-0** [comment]
I see there is "libzip-c" in NuGet already, which seems quite up-to-date.
We do not add packaging information for packaging systems into our repository.
Thank you for packaging libzip!

**Pull request closed without merging**
