### PR TITLE
Attempt to fix appveyor build

### PR DESCRIPTION
**Pull request by scribam**

### CODE REVIEW

**Comment by 0-wiz-0** [comment]
Thank you for looking at fixing the appveyor build!
The proposed patch is incorrect though. As you can see in https://ci.appveyor.com/project/nih-at/libzip/builds/50232046/job/oq2p1n7arprtib7y zlib, liblzma and zstd are not found by the build. (Which is the whole point of using vcpkg, to provide these dependencies.)

**Comment by scribam** [comment]
@0-wiz-0 Are you sure this is incorrect?
When I look at the CMake configure step from your link, I can read:
>-- Found ZLIB: optimized;C:/projects/libzip/build/vcpkg_installed/x64-windows/lib/zlib.lib;debug;C:/projects/libzip/build/vcpkg_installed/x64-windows/debug/lib/zlibd.lib (found suitable version "1.3.1", minimum required is "1.1.2")
-- Found BZip2: optimized;C:/projects/libzip/build/vcpkg_installed/x64-windows/lib/bz2.lib;debug;C:/projects/libzip/build/vcpkg_installed/x64-windows/debug/lib/bz2d.lib (found version "1.0.8")
[...]
-- Found LibLZMA: optimized;C:/projects/libzip/build/vcpkg_installed/x64-windows/lib/lzma.lib;debug;C:/projects/libzip/build/vcpkg_installed/x64-windows/debug/lib/lzma.lib (found suitable version "5.4.4", minimum required is "5.2")
[...]
-- Found zstd: C:/projects/libzip/build/vcpkg_installed/x64-windows/debug/lib/zstd.lib (Required is at least version "1.3.6")

Also, these files are included in the compilation process:
- zip_algorithm_bzip2.c
- zip_algorithm_xz.c
- zip_algorithm_zstd.c

**Comment by 0-wiz-0** [comment]
Ok, that is weird. Perhaps I misinterpreted something.

However, can you please explain how vcpkg knows to install these three packages after your patch?

**Comment by scribam** [comment]
With this file https://github.com/nih-at/libzip/blob/main/vcpkg.json

> Manifest mode uses declarative JSON files to describe metadata about your project or package. In any case, the name of this file is [vcpkg.json](https://learn.microsoft.com/en-us/vcpkg/reference/vcpkg-json).

> Manifest mode is engaged by running the vcpkg install command while there's a manifest file (vcpkg.json) in the working directory.

Source: https://learn.microsoft.com/en-us/vcpkg/concepts/manifest-mode

**Comment by 0-wiz-0** [comment]
Thanks!

**Pull request merged**
