### PR TITLE
zip adds zstd compression algorithm support

### PR DESCRIPTION
**Pull request by fcharlie**
Recently, the zip specification file added 93 as the magic number of the zstd algorithm (initially 20, but WinZip used 93 and later changed to 93). This PR mainly implements support for zstd. This PR may not be tested enough, but I Here, unzipping the zip(zstd) file is successful.

It should be noted that this version does not implement support for compression levels, and may require some minor adjustments.

zip(zstd) related:

https://github.com/mcmilk/7-Zip-zstd/issues/132
https://github.com/mholt/archiver/pull/223
https://github.com/nmoinvaz/minizip/issues/498

@ipaucek4680 If you are interested, you can try it.

### CODE REVIEW

**Comment by ipaucek4680** [comment]
I can confirm that extraction of Zstd ZIP file (created by WinZip) is working.

For compression/modification, `src/ziptool.c` may need to be edited as well? (Reference: a91b3c4 and cc5b86f)

We may also need to set the "version needed to extract".
Although the latest APPNOTE Section 4.4.3.2 does not state the minimum feature version for Zstd, it should be 6.3 (Zstd is added to the specification in revision 6.3.7).
However, it looks like WinZip just sets the version needed to extract to 20 (i.e. 2.0) for Zstd ZIP.

**Comment by fcharlie** [comment]
@ipaucek4680 I’m not sure which value `version_needed` should be set to, I didn’t install WinZip

**Comment by ipaucek4680** [comment]
This is a test file created by WinZip:
[test-zstd.zip](https://github.com/nih-at/libzip/files/4808007/test-zstd.zip)

If you run `7z l -slt test-zstd.zip`, you should see something like:
```
Path = DOC/README.md
Folder = -
Size = 6837
Packed Size = 2435
Modified = 2020-05-30 11:57:14
Created = 2020-05-30 15:53:32
Accessed = 2020-05-30 12:39:49
Attributes = 
Encrypted = -
Comment = 
CRC = 9EF8FDFF
Method = 93
Host OS = FAT
Version = 20
Volume Index = 0
```
So I believe that `Version = 20` indicates that WinZip sets `version_needed` to 2.0.

**Comment by fcharlie** [comment]
@ipaucek4680 already updated

**Comment by ipaucek4680** [comment]
Thanks.

I noticed that this repository contains a copy of the APPNOTE.txt, but section 1.4.2 states that "any reproduction or distribution of this document in whole or in part without prior written permission from PKWARE is strictly prohibited"......

**Comment by fcharlie** [comment]
@ipaucek4680 APPNOTE.txt already existed before. Is it necessary to reauthorize to update APPNOTE.txt? I am not very clear about this. If there is a problem, I will withdraw the APPNOTE.txt update.

**Comment by fcharlie** [comment]
@ipaucek4680 APPNOTE.txt already existed before. Is it necessary to reauthorize to update APPNOTE.txt? I am not very clear about this. If there is a problem, I will withdraw the APPNOTE.txt update.

**Comment by fcharlie** [comment]
@ipaucek4680 I have undo the update of appnote.txt

**Comment by ipaucek4680** [comment]
Well, according to the Git history, the file is added in 2004 (16 years ago) and the commit messages do not say whether the developers were authorized to maintain a copy of it in the repo......

@0-wiz-0
Any thoughts?

**Comment by fcharlie** [comment]
@0-wiz-0

**Comment by 0-wiz-0** [comment]
Thank you! We cleaned it up and merged it.

**Pull request merged**
